# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor/monitor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='monitor/monitor.proto',
  package='cc.arduino.cli.monitor',
  syntax='proto3',
  serialized_options=b'Z*github.com/arduino/arduino-cli/rpc/monitor',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15monitor/monitor.proto\x12\x16\x63\x63.arduino.cli.monitor\x1a\x1cgoogle/protobuf/struct.proto\"m\n\x10StreamingOpenReq\x12>\n\rmonitorConfig\x18\x01 \x01(\x0b\x32%.cc.arduino.cli.monitor.MonitorConfigH\x00\x12\x0e\n\x04\x64\x61ta\x18\x02 \x01(\x0cH\x00\x42\t\n\x07\x63ontent\"\xac\x01\n\rMonitorConfig\x12\x0e\n\x06target\x18\x01 \x01(\t\x12>\n\x04type\x18\x02 \x01(\x0e\x32\x30.cc.arduino.cli.monitor.MonitorConfig.TargetType\x12\x31\n\x10\x61\x64\x64itionalConfig\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\"\x18\n\nTargetType\x12\n\n\x06SERIAL\x10\x00\"!\n\x11StreamingOpenResp\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32u\n\x07Monitor\x12j\n\rStreamingOpen\x12(.cc.arduino.cli.monitor.StreamingOpenReq\x1a).cc.arduino.cli.monitor.StreamingOpenResp\"\x00(\x01\x30\x01\x42,Z*github.com/arduino/arduino-cli/rpc/monitorb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])



_MONITORCONFIG_TARGETTYPE = _descriptor.EnumDescriptor(
  name='TargetType',
  full_name='cc.arduino.cli.monitor.MonitorConfig.TargetType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SERIAL', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=339,
  serialized_end=363,
)
_sym_db.RegisterEnumDescriptor(_MONITORCONFIG_TARGETTYPE)


_STREAMINGOPENREQ = _descriptor.Descriptor(
  name='StreamingOpenReq',
  full_name='cc.arduino.cli.monitor.StreamingOpenReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='monitorConfig', full_name='cc.arduino.cli.monitor.StreamingOpenReq.monitorConfig', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='cc.arduino.cli.monitor.StreamingOpenReq.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='content', full_name='cc.arduino.cli.monitor.StreamingOpenReq.content',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=79,
  serialized_end=188,
)


_MONITORCONFIG = _descriptor.Descriptor(
  name='MonitorConfig',
  full_name='cc.arduino.cli.monitor.MonitorConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='target', full_name='cc.arduino.cli.monitor.MonitorConfig.target', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='cc.arduino.cli.monitor.MonitorConfig.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='additionalConfig', full_name='cc.arduino.cli.monitor.MonitorConfig.additionalConfig', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MONITORCONFIG_TARGETTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=363,
)


_STREAMINGOPENRESP = _descriptor.Descriptor(
  name='StreamingOpenResp',
  full_name='cc.arduino.cli.monitor.StreamingOpenResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='cc.arduino.cli.monitor.StreamingOpenResp.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=365,
  serialized_end=398,
)

_STREAMINGOPENREQ.fields_by_name['monitorConfig'].message_type = _MONITORCONFIG
_STREAMINGOPENREQ.oneofs_by_name['content'].fields.append(
  _STREAMINGOPENREQ.fields_by_name['monitorConfig'])
_STREAMINGOPENREQ.fields_by_name['monitorConfig'].containing_oneof = _STREAMINGOPENREQ.oneofs_by_name['content']
_STREAMINGOPENREQ.oneofs_by_name['content'].fields.append(
  _STREAMINGOPENREQ.fields_by_name['data'])
_STREAMINGOPENREQ.fields_by_name['data'].containing_oneof = _STREAMINGOPENREQ.oneofs_by_name['content']
_MONITORCONFIG.fields_by_name['type'].enum_type = _MONITORCONFIG_TARGETTYPE
_MONITORCONFIG.fields_by_name['additionalConfig'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_MONITORCONFIG_TARGETTYPE.containing_type = _MONITORCONFIG
DESCRIPTOR.message_types_by_name['StreamingOpenReq'] = _STREAMINGOPENREQ
DESCRIPTOR.message_types_by_name['MonitorConfig'] = _MONITORCONFIG
DESCRIPTOR.message_types_by_name['StreamingOpenResp'] = _STREAMINGOPENRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StreamingOpenReq = _reflection.GeneratedProtocolMessageType('StreamingOpenReq', (_message.Message,), {
  'DESCRIPTOR' : _STREAMINGOPENREQ,
  '__module__' : 'monitor.monitor_pb2'
  # @@protoc_insertion_point(class_scope:cc.arduino.cli.monitor.StreamingOpenReq)
  })
_sym_db.RegisterMessage(StreamingOpenReq)

MonitorConfig = _reflection.GeneratedProtocolMessageType('MonitorConfig', (_message.Message,), {
  'DESCRIPTOR' : _MONITORCONFIG,
  '__module__' : 'monitor.monitor_pb2'
  # @@protoc_insertion_point(class_scope:cc.arduino.cli.monitor.MonitorConfig)
  })
_sym_db.RegisterMessage(MonitorConfig)

StreamingOpenResp = _reflection.GeneratedProtocolMessageType('StreamingOpenResp', (_message.Message,), {
  'DESCRIPTOR' : _STREAMINGOPENRESP,
  '__module__' : 'monitor.monitor_pb2'
  # @@protoc_insertion_point(class_scope:cc.arduino.cli.monitor.StreamingOpenResp)
  })
_sym_db.RegisterMessage(StreamingOpenResp)


DESCRIPTOR._options = None

_MONITOR = _descriptor.ServiceDescriptor(
  name='Monitor',
  full_name='cc.arduino.cli.monitor.Monitor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=400,
  serialized_end=517,
  methods=[
  _descriptor.MethodDescriptor(
    name='StreamingOpen',
    full_name='cc.arduino.cli.monitor.Monitor.StreamingOpen',
    index=0,
    containing_service=None,
    input_type=_STREAMINGOPENREQ,
    output_type=_STREAMINGOPENRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MONITOR)

DESCRIPTOR.services_by_name['Monitor'] = _MONITOR

# @@protoc_insertion_point(module_scope)
