# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from monitor import monitor_pb2 as monitor_dot_monitor__pb2


class MonitorStub(object):
    """Service that abstracts a Monitor usage
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamingOpen = channel.stream_stream(
                '/cc.arduino.cli.monitor.Monitor/StreamingOpen',
                request_serializer=monitor_dot_monitor__pb2.StreamingOpenReq.SerializeToString,
                response_deserializer=monitor_dot_monitor__pb2.StreamingOpenResp.FromString,
                )


class MonitorServicer(object):
    """Service that abstracts a Monitor usage
    """

    def StreamingOpen(self, request_iterator, context):
        """Open a bidirectional monitor stream. This can be used to implement
        something similar to the Arduino IDE's Serial Monitor.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MonitorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamingOpen': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamingOpen,
                    request_deserializer=monitor_dot_monitor__pb2.StreamingOpenReq.FromString,
                    response_serializer=monitor_dot_monitor__pb2.StreamingOpenResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cc.arduino.cli.monitor.Monitor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Monitor(object):
    """Service that abstracts a Monitor usage
    """

    @staticmethod
    def StreamingOpen(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/cc.arduino.cli.monitor.Monitor/StreamingOpen',
            monitor_dot_monitor__pb2.StreamingOpenReq.SerializeToString,
            monitor_dot_monitor__pb2.StreamingOpenResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
