# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commands/common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='commands/common.proto',
  package='cc.arduino.cli.commands',
  syntax='proto3',
  serialized_options=b'Z+github.com/arduino/arduino-cli/rpc/commands',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x63ommands/common.proto\x12\x17\x63\x63.arduino.cli.commands\"\x16\n\x08Instance\x12\n\n\x02id\x18\x01 \x01(\x05\"h\n\x10\x44ownloadProgress\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0c\n\x04\x66ile\x18\x02 \x01(\t\x12\x12\n\ntotal_size\x18\x03 \x01(\x03\x12\x12\n\ndownloaded\x18\x04 \x01(\x03\x12\x11\n\tcompleted\x18\x05 \x01(\x08\"@\n\x0cTaskProgress\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\tcompleted\x18\x03 \x01(\x08\"8\n\nProgrammer\x12\x10\n\x08platform\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\tB-Z+github.com/arduino/arduino-cli/rpc/commandsb\x06proto3'
)




_INSTANCE = _descriptor.Descriptor(
  name='Instance',
  full_name='cc.arduino.cli.commands.Instance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='cc.arduino.cli.commands.Instance.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=72,
)


_DOWNLOADPROGRESS = _descriptor.Descriptor(
  name='DownloadProgress',
  full_name='cc.arduino.cli.commands.DownloadProgress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='cc.arduino.cli.commands.DownloadProgress.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file', full_name='cc.arduino.cli.commands.DownloadProgress.file', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_size', full_name='cc.arduino.cli.commands.DownloadProgress.total_size', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='downloaded', full_name='cc.arduino.cli.commands.DownloadProgress.downloaded', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='completed', full_name='cc.arduino.cli.commands.DownloadProgress.completed', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=178,
)


_TASKPROGRESS = _descriptor.Descriptor(
  name='TaskProgress',
  full_name='cc.arduino.cli.commands.TaskProgress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='cc.arduino.cli.commands.TaskProgress.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='cc.arduino.cli.commands.TaskProgress.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='completed', full_name='cc.arduino.cli.commands.TaskProgress.completed', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=244,
)


_PROGRAMMER = _descriptor.Descriptor(
  name='Programmer',
  full_name='cc.arduino.cli.commands.Programmer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='platform', full_name='cc.arduino.cli.commands.Programmer.platform', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='cc.arduino.cli.commands.Programmer.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='cc.arduino.cli.commands.Programmer.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=302,
)

DESCRIPTOR.message_types_by_name['Instance'] = _INSTANCE
DESCRIPTOR.message_types_by_name['DownloadProgress'] = _DOWNLOADPROGRESS
DESCRIPTOR.message_types_by_name['TaskProgress'] = _TASKPROGRESS
DESCRIPTOR.message_types_by_name['Programmer'] = _PROGRAMMER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Instance = _reflection.GeneratedProtocolMessageType('Instance', (_message.Message,), {
  'DESCRIPTOR' : _INSTANCE,
  '__module__' : 'commands.common_pb2'
  # @@protoc_insertion_point(class_scope:cc.arduino.cli.commands.Instance)
  })
_sym_db.RegisterMessage(Instance)

DownloadProgress = _reflection.GeneratedProtocolMessageType('DownloadProgress', (_message.Message,), {
  'DESCRIPTOR' : _DOWNLOADPROGRESS,
  '__module__' : 'commands.common_pb2'
  # @@protoc_insertion_point(class_scope:cc.arduino.cli.commands.DownloadProgress)
  })
_sym_db.RegisterMessage(DownloadProgress)

TaskProgress = _reflection.GeneratedProtocolMessageType('TaskProgress', (_message.Message,), {
  'DESCRIPTOR' : _TASKPROGRESS,
  '__module__' : 'commands.common_pb2'
  # @@protoc_insertion_point(class_scope:cc.arduino.cli.commands.TaskProgress)
  })
_sym_db.RegisterMessage(TaskProgress)

Programmer = _reflection.GeneratedProtocolMessageType('Programmer', (_message.Message,), {
  'DESCRIPTOR' : _PROGRAMMER,
  '__module__' : 'commands.common_pb2'
  # @@protoc_insertion_point(class_scope:cc.arduino.cli.commands.Programmer)
  })
_sym_db.RegisterMessage(Programmer)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
