# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commands/compile.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from commands import common_pb2 as commands_dot_common__pb2
from commands import lib_pb2 as commands_dot_lib__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='commands/compile.proto',
  package='cc.arduino.cli.commands',
  syntax='proto3',
  serialized_options=b'Z+github.com/arduino/arduino-cli/rpc/commands',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x63ommands/compile.proto\x12\x17\x63\x63.arduino.cli.commands\x1a\x15\x63ommands/common.proto\x1a\x12\x63ommands/lib.proto\"\xbf\x04\n\nCompileReq\x12\x33\n\x08instance\x18\x01 \x01(\x0b\x32!.cc.arduino.cli.commands.Instance\x12\x0c\n\x04\x66qbn\x18\x02 \x01(\t\x12\x12\n\nsketchPath\x18\x03 \x01(\t\x12\x16\n\x0eshowProperties\x18\x04 \x01(\x08\x12\x12\n\npreprocess\x18\x05 \x01(\x08\x12\x16\n\x0e\x62uildCachePath\x18\x06 \x01(\t\x12\x11\n\tbuildPath\x18\x07 \x01(\t\x12\x17\n\x0f\x62uildProperties\x18\x08 \x03(\t\x12\x10\n\x08warnings\x18\t \x01(\t\x12\x0f\n\x07verbose\x18\n \x01(\x08\x12\r\n\x05quiet\x18\x0b \x01(\x08\x12\x0e\n\x06vidPid\x18\x0c \x01(\t\x12\x0c\n\x04jobs\x18\x0e \x01(\x05\x12\x11\n\tlibraries\x18\x0f \x03(\t\x12\x18\n\x10optimizeForDebug\x18\x10 \x01(\x08\x12\x12\n\nexport_dir\x18\x12 \x01(\t\x12\r\n\x05\x63lean\x18\x13 \x01(\x08\x12\x17\n\x0f\x65xport_binaries\x18\x14 \x01(\x08\x12(\n create_compilation_database_only\x18\x15 \x01(\x08\x12P\n\x0fsource_override\x18\x16 \x03(\x0b\x32\x37.cc.arduino.cli.commands.CompileReq.SourceOverrideEntry\x1a\x35\n\x13SourceOverrideEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xd5\x01\n\x0b\x43ompileResp\x12\x12\n\nout_stream\x18\x01 \x01(\x0c\x12\x12\n\nerr_stream\x18\x02 \x01(\x0c\x12\x12\n\nbuild_path\x18\x03 \x01(\t\x12\x38\n\x0eused_libraries\x18\x04 \x03(\x0b\x32 .cc.arduino.cli.commands.Library\x12P\n\x18\x65xecutable_sections_size\x18\x05 \x03(\x0b\x32..cc.arduino.cli.commands.ExecutableSectionSize\"D\n\x15\x45xecutableSectionSize\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x03\x12\x0f\n\x07maxSize\x18\x03 \x01(\x03\x42-Z+github.com/arduino/arduino-cli/rpc/commandsb\x06proto3'
  ,
  dependencies=[commands_dot_common__pb2.DESCRIPTOR,commands_dot_lib__pb2.DESCRIPTOR,])




_COMPILEREQ_SOURCEOVERRIDEENTRY = _descriptor.Descriptor(
  name='SourceOverrideEntry',
  full_name='cc.arduino.cli.commands.CompileReq.SourceOverrideEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='cc.arduino.cli.commands.CompileReq.SourceOverrideEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='cc.arduino.cli.commands.CompileReq.SourceOverrideEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=617,
  serialized_end=670,
)

_COMPILEREQ = _descriptor.Descriptor(
  name='CompileReq',
  full_name='cc.arduino.cli.commands.CompileReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance', full_name='cc.arduino.cli.commands.CompileReq.instance', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fqbn', full_name='cc.arduino.cli.commands.CompileReq.fqbn', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sketchPath', full_name='cc.arduino.cli.commands.CompileReq.sketchPath', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='showProperties', full_name='cc.arduino.cli.commands.CompileReq.showProperties', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='preprocess', full_name='cc.arduino.cli.commands.CompileReq.preprocess', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='buildCachePath', full_name='cc.arduino.cli.commands.CompileReq.buildCachePath', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='buildPath', full_name='cc.arduino.cli.commands.CompileReq.buildPath', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='buildProperties', full_name='cc.arduino.cli.commands.CompileReq.buildProperties', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='warnings', full_name='cc.arduino.cli.commands.CompileReq.warnings', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='verbose', full_name='cc.arduino.cli.commands.CompileReq.verbose', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quiet', full_name='cc.arduino.cli.commands.CompileReq.quiet', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vidPid', full_name='cc.arduino.cli.commands.CompileReq.vidPid', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='jobs', full_name='cc.arduino.cli.commands.CompileReq.jobs', index=12,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='libraries', full_name='cc.arduino.cli.commands.CompileReq.libraries', index=13,
      number=15, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='optimizeForDebug', full_name='cc.arduino.cli.commands.CompileReq.optimizeForDebug', index=14,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='export_dir', full_name='cc.arduino.cli.commands.CompileReq.export_dir', index=15,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clean', full_name='cc.arduino.cli.commands.CompileReq.clean', index=16,
      number=19, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='export_binaries', full_name='cc.arduino.cli.commands.CompileReq.export_binaries', index=17,
      number=20, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='create_compilation_database_only', full_name='cc.arduino.cli.commands.CompileReq.create_compilation_database_only', index=18,
      number=21, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source_override', full_name='cc.arduino.cli.commands.CompileReq.source_override', index=19,
      number=22, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_COMPILEREQ_SOURCEOVERRIDEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=670,
)


_COMPILERESP = _descriptor.Descriptor(
  name='CompileResp',
  full_name='cc.arduino.cli.commands.CompileResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='out_stream', full_name='cc.arduino.cli.commands.CompileResp.out_stream', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='err_stream', full_name='cc.arduino.cli.commands.CompileResp.err_stream', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='build_path', full_name='cc.arduino.cli.commands.CompileResp.build_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='used_libraries', full_name='cc.arduino.cli.commands.CompileResp.used_libraries', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='executable_sections_size', full_name='cc.arduino.cli.commands.CompileResp.executable_sections_size', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=673,
  serialized_end=886,
)


_EXECUTABLESECTIONSIZE = _descriptor.Descriptor(
  name='ExecutableSectionSize',
  full_name='cc.arduino.cli.commands.ExecutableSectionSize',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='cc.arduino.cli.commands.ExecutableSectionSize.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size', full_name='cc.arduino.cli.commands.ExecutableSectionSize.size', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='maxSize', full_name='cc.arduino.cli.commands.ExecutableSectionSize.maxSize', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=888,
  serialized_end=956,
)

_COMPILEREQ_SOURCEOVERRIDEENTRY.containing_type = _COMPILEREQ
_COMPILEREQ.fields_by_name['instance'].message_type = commands_dot_common__pb2._INSTANCE
_COMPILEREQ.fields_by_name['source_override'].message_type = _COMPILEREQ_SOURCEOVERRIDEENTRY
_COMPILERESP.fields_by_name['used_libraries'].message_type = commands_dot_lib__pb2._LIBRARY
_COMPILERESP.fields_by_name['executable_sections_size'].message_type = _EXECUTABLESECTIONSIZE
DESCRIPTOR.message_types_by_name['CompileReq'] = _COMPILEREQ
DESCRIPTOR.message_types_by_name['CompileResp'] = _COMPILERESP
DESCRIPTOR.message_types_by_name['ExecutableSectionSize'] = _EXECUTABLESECTIONSIZE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CompileReq = _reflection.GeneratedProtocolMessageType('CompileReq', (_message.Message,), {

  'SourceOverrideEntry' : _reflection.GeneratedProtocolMessageType('SourceOverrideEntry', (_message.Message,), {
    'DESCRIPTOR' : _COMPILEREQ_SOURCEOVERRIDEENTRY,
    '__module__' : 'commands.compile_pb2'
    # @@protoc_insertion_point(class_scope:cc.arduino.cli.commands.CompileReq.SourceOverrideEntry)
    })
  ,
  'DESCRIPTOR' : _COMPILEREQ,
  '__module__' : 'commands.compile_pb2'
  # @@protoc_insertion_point(class_scope:cc.arduino.cli.commands.CompileReq)
  })
_sym_db.RegisterMessage(CompileReq)
_sym_db.RegisterMessage(CompileReq.SourceOverrideEntry)

CompileResp = _reflection.GeneratedProtocolMessageType('CompileResp', (_message.Message,), {
  'DESCRIPTOR' : _COMPILERESP,
  '__module__' : 'commands.compile_pb2'
  # @@protoc_insertion_point(class_scope:cc.arduino.cli.commands.CompileResp)
  })
_sym_db.RegisterMessage(CompileResp)

ExecutableSectionSize = _reflection.GeneratedProtocolMessageType('ExecutableSectionSize', (_message.Message,), {
  'DESCRIPTOR' : _EXECUTABLESECTIONSIZE,
  '__module__' : 'commands.compile_pb2'
  # @@protoc_insertion_point(class_scope:cc.arduino.cli.commands.ExecutableSectionSize)
  })
_sym_db.RegisterMessage(ExecutableSectionSize)


DESCRIPTOR._options = None
_COMPILEREQ_SOURCEOVERRIDEENTRY._options = None
# @@protoc_insertion_point(module_scope)
