# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commands/upload.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from commands import common_pb2 as commands_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='commands/upload.proto',
  package='cc.arduino.cli.commands',
  syntax='proto3',
  serialized_options=b'Z+github.com/arduino/arduino-cli/rpc/commands',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x63ommands/upload.proto\x12\x17\x63\x63.arduino.cli.commands\x1a\x15\x63ommands/common.proto\"\xcf\x01\n\tUploadReq\x12\x33\n\x08instance\x18\x01 \x01(\x0b\x32!.cc.arduino.cli.commands.Instance\x12\x0c\n\x04\x66qbn\x18\x02 \x01(\t\x12\x13\n\x0bsketch_path\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\t\x12\x0f\n\x07verbose\x18\x05 \x01(\x08\x12\x0e\n\x06verify\x18\x06 \x01(\x08\x12\x13\n\x0bimport_file\x18\x07 \x01(\t\x12\x12\n\nimport_dir\x18\x08 \x01(\t\x12\x12\n\nprogrammer\x18\t \x01(\t\"4\n\nUploadResp\x12\x12\n\nout_stream\x18\x01 \x01(\x0c\x12\x12\n\nerr_stream\x18\x02 \x01(\x0c\"\xde\x01\n\x18UploadUsingProgrammerReq\x12\x33\n\x08instance\x18\x01 \x01(\x0b\x32!.cc.arduino.cli.commands.Instance\x12\x0c\n\x04\x66qbn\x18\x02 \x01(\t\x12\x13\n\x0bsketch_path\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\t\x12\x0f\n\x07verbose\x18\x05 \x01(\x08\x12\x0e\n\x06verify\x18\x06 \x01(\x08\x12\x13\n\x0bimport_file\x18\x07 \x01(\t\x12\x12\n\nimport_dir\x18\x08 \x01(\t\x12\x12\n\nprogrammer\x18\t \x01(\t\"C\n\x19UploadUsingProgrammerResp\x12\x12\n\nout_stream\x18\x01 \x01(\x0c\x12\x12\n\nerr_stream\x18\x02 \x01(\x0c\"\x99\x01\n\x11\x42urnBootloaderReq\x12\x33\n\x08instance\x18\x01 \x01(\x0b\x32!.cc.arduino.cli.commands.Instance\x12\x0c\n\x04\x66qbn\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\t\x12\x0f\n\x07verbose\x18\x04 \x01(\x08\x12\x0e\n\x06verify\x18\x05 \x01(\x08\x12\x12\n\nprogrammer\x18\x06 \x01(\t\"<\n\x12\x42urnBootloaderResp\x12\x12\n\nout_stream\x18\x01 \x01(\x0c\x12\x12\n\nerr_stream\x18\x02 \x01(\x0c\"i\n$ListProgrammersAvailableForUploadReq\x12\x33\n\x08instance\x18\x01 \x01(\x0b\x32!.cc.arduino.cli.commands.Instance\x12\x0c\n\x04\x66qbn\x18\x02 \x01(\t\"a\n%ListProgrammersAvailableForUploadResp\x12\x38\n\x0bprogrammers\x18\x01 \x03(\x0b\x32#.cc.arduino.cli.commands.ProgrammerB-Z+github.com/arduino/arduino-cli/rpc/commandsb\x06proto3'
  ,
  dependencies=[commands_dot_common__pb2.DESCRIPTOR,])




_UPLOADREQ = _descriptor.Descriptor(
  name='UploadReq',
  full_name='cc.arduino.cli.commands.UploadReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance', full_name='cc.arduino.cli.commands.UploadReq.instance', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fqbn', full_name='cc.arduino.cli.commands.UploadReq.fqbn', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sketch_path', full_name='cc.arduino.cli.commands.UploadReq.sketch_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='cc.arduino.cli.commands.UploadReq.port', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='verbose', full_name='cc.arduino.cli.commands.UploadReq.verbose', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='verify', full_name='cc.arduino.cli.commands.UploadReq.verify', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='import_file', full_name='cc.arduino.cli.commands.UploadReq.import_file', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='import_dir', full_name='cc.arduino.cli.commands.UploadReq.import_dir', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='programmer', full_name='cc.arduino.cli.commands.UploadReq.programmer', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=281,
)


_UPLOADRESP = _descriptor.Descriptor(
  name='UploadResp',
  full_name='cc.arduino.cli.commands.UploadResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='out_stream', full_name='cc.arduino.cli.commands.UploadResp.out_stream', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='err_stream', full_name='cc.arduino.cli.commands.UploadResp.err_stream', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=335,
)


_UPLOADUSINGPROGRAMMERREQ = _descriptor.Descriptor(
  name='UploadUsingProgrammerReq',
  full_name='cc.arduino.cli.commands.UploadUsingProgrammerReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance', full_name='cc.arduino.cli.commands.UploadUsingProgrammerReq.instance', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fqbn', full_name='cc.arduino.cli.commands.UploadUsingProgrammerReq.fqbn', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sketch_path', full_name='cc.arduino.cli.commands.UploadUsingProgrammerReq.sketch_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='cc.arduino.cli.commands.UploadUsingProgrammerReq.port', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='verbose', full_name='cc.arduino.cli.commands.UploadUsingProgrammerReq.verbose', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='verify', full_name='cc.arduino.cli.commands.UploadUsingProgrammerReq.verify', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='import_file', full_name='cc.arduino.cli.commands.UploadUsingProgrammerReq.import_file', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='import_dir', full_name='cc.arduino.cli.commands.UploadUsingProgrammerReq.import_dir', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='programmer', full_name='cc.arduino.cli.commands.UploadUsingProgrammerReq.programmer', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=338,
  serialized_end=560,
)


_UPLOADUSINGPROGRAMMERRESP = _descriptor.Descriptor(
  name='UploadUsingProgrammerResp',
  full_name='cc.arduino.cli.commands.UploadUsingProgrammerResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='out_stream', full_name='cc.arduino.cli.commands.UploadUsingProgrammerResp.out_stream', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='err_stream', full_name='cc.arduino.cli.commands.UploadUsingProgrammerResp.err_stream', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=562,
  serialized_end=629,
)


_BURNBOOTLOADERREQ = _descriptor.Descriptor(
  name='BurnBootloaderReq',
  full_name='cc.arduino.cli.commands.BurnBootloaderReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance', full_name='cc.arduino.cli.commands.BurnBootloaderReq.instance', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fqbn', full_name='cc.arduino.cli.commands.BurnBootloaderReq.fqbn', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='cc.arduino.cli.commands.BurnBootloaderReq.port', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='verbose', full_name='cc.arduino.cli.commands.BurnBootloaderReq.verbose', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='verify', full_name='cc.arduino.cli.commands.BurnBootloaderReq.verify', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='programmer', full_name='cc.arduino.cli.commands.BurnBootloaderReq.programmer', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=632,
  serialized_end=785,
)


_BURNBOOTLOADERRESP = _descriptor.Descriptor(
  name='BurnBootloaderResp',
  full_name='cc.arduino.cli.commands.BurnBootloaderResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='out_stream', full_name='cc.arduino.cli.commands.BurnBootloaderResp.out_stream', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='err_stream', full_name='cc.arduino.cli.commands.BurnBootloaderResp.err_stream', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=787,
  serialized_end=847,
)


_LISTPROGRAMMERSAVAILABLEFORUPLOADREQ = _descriptor.Descriptor(
  name='ListProgrammersAvailableForUploadReq',
  full_name='cc.arduino.cli.commands.ListProgrammersAvailableForUploadReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance', full_name='cc.arduino.cli.commands.ListProgrammersAvailableForUploadReq.instance', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fqbn', full_name='cc.arduino.cli.commands.ListProgrammersAvailableForUploadReq.fqbn', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=849,
  serialized_end=954,
)


_LISTPROGRAMMERSAVAILABLEFORUPLOADRESP = _descriptor.Descriptor(
  name='ListProgrammersAvailableForUploadResp',
  full_name='cc.arduino.cli.commands.ListProgrammersAvailableForUploadResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='programmers', full_name='cc.arduino.cli.commands.ListProgrammersAvailableForUploadResp.programmers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=956,
  serialized_end=1053,
)

_UPLOADREQ.fields_by_name['instance'].message_type = commands_dot_common__pb2._INSTANCE
_UPLOADUSINGPROGRAMMERREQ.fields_by_name['instance'].message_type = commands_dot_common__pb2._INSTANCE
_BURNBOOTLOADERREQ.fields_by_name['instance'].message_type = commands_dot_common__pb2._INSTANCE
_LISTPROGRAMMERSAVAILABLEFORUPLOADREQ.fields_by_name['instance'].message_type = commands_dot_common__pb2._INSTANCE
_LISTPROGRAMMERSAVAILABLEFORUPLOADRESP.fields_by_name['programmers'].message_type = commands_dot_common__pb2._PROGRAMMER
DESCRIPTOR.message_types_by_name['UploadReq'] = _UPLOADREQ
DESCRIPTOR.message_types_by_name['UploadResp'] = _UPLOADRESP
DESCRIPTOR.message_types_by_name['UploadUsingProgrammerReq'] = _UPLOADUSINGPROGRAMMERREQ
DESCRIPTOR.message_types_by_name['UploadUsingProgrammerResp'] = _UPLOADUSINGPROGRAMMERRESP
DESCRIPTOR.message_types_by_name['BurnBootloaderReq'] = _BURNBOOTLOADERREQ
DESCRIPTOR.message_types_by_name['BurnBootloaderResp'] = _BURNBOOTLOADERRESP
DESCRIPTOR.message_types_by_name['ListProgrammersAvailableForUploadReq'] = _LISTPROGRAMMERSAVAILABLEFORUPLOADREQ
DESCRIPTOR.message_types_by_name['ListProgrammersAvailableForUploadResp'] = _LISTPROGRAMMERSAVAILABLEFORUPLOADRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UploadReq = _reflection.GeneratedProtocolMessageType('UploadReq', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADREQ,
  '__module__' : 'commands.upload_pb2'
  # @@protoc_insertion_point(class_scope:cc.arduino.cli.commands.UploadReq)
  })
_sym_db.RegisterMessage(UploadReq)

UploadResp = _reflection.GeneratedProtocolMessageType('UploadResp', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADRESP,
  '__module__' : 'commands.upload_pb2'
  # @@protoc_insertion_point(class_scope:cc.arduino.cli.commands.UploadResp)
  })
_sym_db.RegisterMessage(UploadResp)

UploadUsingProgrammerReq = _reflection.GeneratedProtocolMessageType('UploadUsingProgrammerReq', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADUSINGPROGRAMMERREQ,
  '__module__' : 'commands.upload_pb2'
  # @@protoc_insertion_point(class_scope:cc.arduino.cli.commands.UploadUsingProgrammerReq)
  })
_sym_db.RegisterMessage(UploadUsingProgrammerReq)

UploadUsingProgrammerResp = _reflection.GeneratedProtocolMessageType('UploadUsingProgrammerResp', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADUSINGPROGRAMMERRESP,
  '__module__' : 'commands.upload_pb2'
  # @@protoc_insertion_point(class_scope:cc.arduino.cli.commands.UploadUsingProgrammerResp)
  })
_sym_db.RegisterMessage(UploadUsingProgrammerResp)

BurnBootloaderReq = _reflection.GeneratedProtocolMessageType('BurnBootloaderReq', (_message.Message,), {
  'DESCRIPTOR' : _BURNBOOTLOADERREQ,
  '__module__' : 'commands.upload_pb2'
  # @@protoc_insertion_point(class_scope:cc.arduino.cli.commands.BurnBootloaderReq)
  })
_sym_db.RegisterMessage(BurnBootloaderReq)

BurnBootloaderResp = _reflection.GeneratedProtocolMessageType('BurnBootloaderResp', (_message.Message,), {
  'DESCRIPTOR' : _BURNBOOTLOADERRESP,
  '__module__' : 'commands.upload_pb2'
  # @@protoc_insertion_point(class_scope:cc.arduino.cli.commands.BurnBootloaderResp)
  })
_sym_db.RegisterMessage(BurnBootloaderResp)

ListProgrammersAvailableForUploadReq = _reflection.GeneratedProtocolMessageType('ListProgrammersAvailableForUploadReq', (_message.Message,), {
  'DESCRIPTOR' : _LISTPROGRAMMERSAVAILABLEFORUPLOADREQ,
  '__module__' : 'commands.upload_pb2'
  # @@protoc_insertion_point(class_scope:cc.arduino.cli.commands.ListProgrammersAvailableForUploadReq)
  })
_sym_db.RegisterMessage(ListProgrammersAvailableForUploadReq)

ListProgrammersAvailableForUploadResp = _reflection.GeneratedProtocolMessageType('ListProgrammersAvailableForUploadResp', (_message.Message,), {
  'DESCRIPTOR' : _LISTPROGRAMMERSAVAILABLEFORUPLOADRESP,
  '__module__' : 'commands.upload_pb2'
  # @@protoc_insertion_point(class_scope:cc.arduino.cli.commands.ListProgrammersAvailableForUploadResp)
  })
_sym_db.RegisterMessage(ListProgrammersAvailableForUploadResp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
