# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: settings/settings.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='settings/settings.proto',
  package='cc.arduino.cli.settings',
  syntax='proto3',
  serialized_options=b'Z+github.com/arduino/arduino-cli/rpc/settings',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17settings/settings.proto\x12\x17\x63\x63.arduino.cli.settings\"\x1b\n\x07RawData\x12\x10\n\x08jsonData\x18\x01 \x01(\t\"&\n\x05Value\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x10\n\x08jsonData\x18\x02 \x01(\t\"\x0f\n\rGetAllRequest\"\x1e\n\x0fGetValueRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x0f\n\rMergeResponse\"\x12\n\x10SetValueResponse2\xde\x02\n\x08Settings\x12R\n\x06GetAll\x12&.cc.arduino.cli.settings.GetAllRequest\x1a .cc.arduino.cli.settings.RawData\x12Q\n\x05Merge\x12 .cc.arduino.cli.settings.RawData\x1a&.cc.arduino.cli.settings.MergeResponse\x12T\n\x08GetValue\x12(.cc.arduino.cli.settings.GetValueRequest\x1a\x1e.cc.arduino.cli.settings.Value\x12U\n\x08SetValue\x12\x1e.cc.arduino.cli.settings.Value\x1a).cc.arduino.cli.settings.SetValueResponseB-Z+github.com/arduino/arduino-cli/rpc/settingsb\x06proto3'
)




_RAWDATA = _descriptor.Descriptor(
  name='RawData',
  full_name='cc.arduino.cli.settings.RawData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='jsonData', full_name='cc.arduino.cli.settings.RawData.jsonData', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=79,
)


_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='cc.arduino.cli.settings.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='cc.arduino.cli.settings.Value.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='jsonData', full_name='cc.arduino.cli.settings.Value.jsonData', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=119,
)


_GETALLREQUEST = _descriptor.Descriptor(
  name='GetAllRequest',
  full_name='cc.arduino.cli.settings.GetAllRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=136,
)


_GETVALUEREQUEST = _descriptor.Descriptor(
  name='GetValueRequest',
  full_name='cc.arduino.cli.settings.GetValueRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='cc.arduino.cli.settings.GetValueRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=168,
)


_MERGERESPONSE = _descriptor.Descriptor(
  name='MergeResponse',
  full_name='cc.arduino.cli.settings.MergeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=185,
)


_SETVALUERESPONSE = _descriptor.Descriptor(
  name='SetValueResponse',
  full_name='cc.arduino.cli.settings.SetValueResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=205,
)

DESCRIPTOR.message_types_by_name['RawData'] = _RAWDATA
DESCRIPTOR.message_types_by_name['Value'] = _VALUE
DESCRIPTOR.message_types_by_name['GetAllRequest'] = _GETALLREQUEST
DESCRIPTOR.message_types_by_name['GetValueRequest'] = _GETVALUEREQUEST
DESCRIPTOR.message_types_by_name['MergeResponse'] = _MERGERESPONSE
DESCRIPTOR.message_types_by_name['SetValueResponse'] = _SETVALUERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RawData = _reflection.GeneratedProtocolMessageType('RawData', (_message.Message,), {
  'DESCRIPTOR' : _RAWDATA,
  '__module__' : 'settings.settings_pb2'
  # @@protoc_insertion_point(class_scope:cc.arduino.cli.settings.RawData)
  })
_sym_db.RegisterMessage(RawData)

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), {
  'DESCRIPTOR' : _VALUE,
  '__module__' : 'settings.settings_pb2'
  # @@protoc_insertion_point(class_scope:cc.arduino.cli.settings.Value)
  })
_sym_db.RegisterMessage(Value)

GetAllRequest = _reflection.GeneratedProtocolMessageType('GetAllRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETALLREQUEST,
  '__module__' : 'settings.settings_pb2'
  # @@protoc_insertion_point(class_scope:cc.arduino.cli.settings.GetAllRequest)
  })
_sym_db.RegisterMessage(GetAllRequest)

GetValueRequest = _reflection.GeneratedProtocolMessageType('GetValueRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETVALUEREQUEST,
  '__module__' : 'settings.settings_pb2'
  # @@protoc_insertion_point(class_scope:cc.arduino.cli.settings.GetValueRequest)
  })
_sym_db.RegisterMessage(GetValueRequest)

MergeResponse = _reflection.GeneratedProtocolMessageType('MergeResponse', (_message.Message,), {
  'DESCRIPTOR' : _MERGERESPONSE,
  '__module__' : 'settings.settings_pb2'
  # @@protoc_insertion_point(class_scope:cc.arduino.cli.settings.MergeResponse)
  })
_sym_db.RegisterMessage(MergeResponse)

SetValueResponse = _reflection.GeneratedProtocolMessageType('SetValueResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETVALUERESPONSE,
  '__module__' : 'settings.settings_pb2'
  # @@protoc_insertion_point(class_scope:cc.arduino.cli.settings.SetValueResponse)
  })
_sym_db.RegisterMessage(SetValueResponse)


DESCRIPTOR._options = None

_SETTINGS = _descriptor.ServiceDescriptor(
  name='Settings',
  full_name='cc.arduino.cli.settings.Settings',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=208,
  serialized_end=558,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAll',
    full_name='cc.arduino.cli.settings.Settings.GetAll',
    index=0,
    containing_service=None,
    input_type=_GETALLREQUEST,
    output_type=_RAWDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Merge',
    full_name='cc.arduino.cli.settings.Settings.Merge',
    index=1,
    containing_service=None,
    input_type=_RAWDATA,
    output_type=_MERGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetValue',
    full_name='cc.arduino.cli.settings.Settings.GetValue',
    index=2,
    containing_service=None,
    input_type=_GETVALUEREQUEST,
    output_type=_VALUE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetValue',
    full_name='cc.arduino.cli.settings.Settings.SetValue',
    index=3,
    containing_service=None,
    input_type=_VALUE,
    output_type=_SETVALUERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SETTINGS)

DESCRIPTOR.services_by_name['Settings'] = _SETTINGS

# @@protoc_insertion_point(module_scope)
