# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: debug/debug.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from commands import common_pb2 as commands_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='debug/debug.proto',
  package='cc.arduino.cli.debug',
  syntax='proto3',
  serialized_options=b'Z(github.com/arduino/arduino-cli/rpc/debug',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x64\x65\x62ug/debug.proto\x12\x14\x63\x63.arduino.cli.debug\x1a\x15\x63ommands/common.proto\"h\n\x08\x44\x65\x62ugReq\x12\x36\n\x08\x64\x65\x62ugReq\x18\x01 \x01(\x0b\x32$.cc.arduino.cli.debug.DebugConfigReq\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x16\n\x0esend_interrupt\x18\x03 \x01(\x08\"\xb3\x01\n\x0e\x44\x65\x62ugConfigReq\x12\x33\n\x08instance\x18\x01 \x01(\x0b\x32!.cc.arduino.cli.commands.Instance\x12\x0c\n\x04\x66qbn\x18\x02 \x01(\t\x12\x13\n\x0bsketch_path\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\t\x12\x13\n\x0binterpreter\x18\x05 \x01(\t\x12\x12\n\nimport_dir\x18\x08 \x01(\t\x12\x12\n\nprogrammer\x18\t \x01(\t\"(\n\tDebugResp\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\xd5\x03\n\x12GetDebugConfigResp\x12\x12\n\nexecutable\x18\x01 \x01(\t\x12\x11\n\ttoolchain\x18\x02 \x01(\t\x12\x16\n\x0etoolchain_path\x18\x03 \x01(\t\x12\x18\n\x10toolchain_prefix\x18\x04 \x01(\t\x12\x0e\n\x06server\x18\x05 \x01(\t\x12\x13\n\x0bserver_path\x18\x06 \x01(\t\x12\x65\n\x17toolchain_configuration\x18\x07 \x03(\x0b\x32\x44.cc.arduino.cli.debug.GetDebugConfigResp.ToolchainConfigurationEntry\x12_\n\x14server_configuration\x18\x08 \x03(\x0b\x32\x41.cc.arduino.cli.debug.GetDebugConfigResp.ServerConfigurationEntry\x1a=\n\x1bToolchainConfigurationEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a:\n\x18ServerConfigurationEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xbb\x01\n\x05\x44\x65\x62ug\x12N\n\x05\x44\x65\x62ug\x12\x1e.cc.arduino.cli.debug.DebugReq\x1a\x1f.cc.arduino.cli.debug.DebugResp\"\x00(\x01\x30\x01\x12\x62\n\x0eGetDebugConfig\x12$.cc.arduino.cli.debug.DebugConfigReq\x1a(.cc.arduino.cli.debug.GetDebugConfigResp\"\x00\x42*Z(github.com/arduino/arduino-cli/rpc/debugb\x06proto3'
  ,
  dependencies=[commands_dot_common__pb2.DESCRIPTOR,])




_DEBUGREQ = _descriptor.Descriptor(
  name='DebugReq',
  full_name='cc.arduino.cli.debug.DebugReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='debugReq', full_name='cc.arduino.cli.debug.DebugReq.debugReq', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='cc.arduino.cli.debug.DebugReq.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='send_interrupt', full_name='cc.arduino.cli.debug.DebugReq.send_interrupt', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=170,
)


_DEBUGCONFIGREQ = _descriptor.Descriptor(
  name='DebugConfigReq',
  full_name='cc.arduino.cli.debug.DebugConfigReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance', full_name='cc.arduino.cli.debug.DebugConfigReq.instance', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fqbn', full_name='cc.arduino.cli.debug.DebugConfigReq.fqbn', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sketch_path', full_name='cc.arduino.cli.debug.DebugConfigReq.sketch_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='cc.arduino.cli.debug.DebugConfigReq.port', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='interpreter', full_name='cc.arduino.cli.debug.DebugConfigReq.interpreter', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='import_dir', full_name='cc.arduino.cli.debug.DebugConfigReq.import_dir', index=5,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='programmer', full_name='cc.arduino.cli.debug.DebugConfigReq.programmer', index=6,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=352,
)


_DEBUGRESP = _descriptor.Descriptor(
  name='DebugResp',
  full_name='cc.arduino.cli.debug.DebugResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='cc.arduino.cli.debug.DebugResp.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='cc.arduino.cli.debug.DebugResp.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=394,
)


_GETDEBUGCONFIGRESP_TOOLCHAINCONFIGURATIONENTRY = _descriptor.Descriptor(
  name='ToolchainConfigurationEntry',
  full_name='cc.arduino.cli.debug.GetDebugConfigResp.ToolchainConfigurationEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='cc.arduino.cli.debug.GetDebugConfigResp.ToolchainConfigurationEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='cc.arduino.cli.debug.GetDebugConfigResp.ToolchainConfigurationEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=745,
  serialized_end=806,
)

_GETDEBUGCONFIGRESP_SERVERCONFIGURATIONENTRY = _descriptor.Descriptor(
  name='ServerConfigurationEntry',
  full_name='cc.arduino.cli.debug.GetDebugConfigResp.ServerConfigurationEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='cc.arduino.cli.debug.GetDebugConfigResp.ServerConfigurationEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='cc.arduino.cli.debug.GetDebugConfigResp.ServerConfigurationEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=808,
  serialized_end=866,
)

_GETDEBUGCONFIGRESP = _descriptor.Descriptor(
  name='GetDebugConfigResp',
  full_name='cc.arduino.cli.debug.GetDebugConfigResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='executable', full_name='cc.arduino.cli.debug.GetDebugConfigResp.executable', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='toolchain', full_name='cc.arduino.cli.debug.GetDebugConfigResp.toolchain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='toolchain_path', full_name='cc.arduino.cli.debug.GetDebugConfigResp.toolchain_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='toolchain_prefix', full_name='cc.arduino.cli.debug.GetDebugConfigResp.toolchain_prefix', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='server', full_name='cc.arduino.cli.debug.GetDebugConfigResp.server', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='server_path', full_name='cc.arduino.cli.debug.GetDebugConfigResp.server_path', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='toolchain_configuration', full_name='cc.arduino.cli.debug.GetDebugConfigResp.toolchain_configuration', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='server_configuration', full_name='cc.arduino.cli.debug.GetDebugConfigResp.server_configuration', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GETDEBUGCONFIGRESP_TOOLCHAINCONFIGURATIONENTRY, _GETDEBUGCONFIGRESP_SERVERCONFIGURATIONENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=397,
  serialized_end=866,
)

_DEBUGREQ.fields_by_name['debugReq'].message_type = _DEBUGCONFIGREQ
_DEBUGCONFIGREQ.fields_by_name['instance'].message_type = commands_dot_common__pb2._INSTANCE
_GETDEBUGCONFIGRESP_TOOLCHAINCONFIGURATIONENTRY.containing_type = _GETDEBUGCONFIGRESP
_GETDEBUGCONFIGRESP_SERVERCONFIGURATIONENTRY.containing_type = _GETDEBUGCONFIGRESP
_GETDEBUGCONFIGRESP.fields_by_name['toolchain_configuration'].message_type = _GETDEBUGCONFIGRESP_TOOLCHAINCONFIGURATIONENTRY
_GETDEBUGCONFIGRESP.fields_by_name['server_configuration'].message_type = _GETDEBUGCONFIGRESP_SERVERCONFIGURATIONENTRY
DESCRIPTOR.message_types_by_name['DebugReq'] = _DEBUGREQ
DESCRIPTOR.message_types_by_name['DebugConfigReq'] = _DEBUGCONFIGREQ
DESCRIPTOR.message_types_by_name['DebugResp'] = _DEBUGRESP
DESCRIPTOR.message_types_by_name['GetDebugConfigResp'] = _GETDEBUGCONFIGRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DebugReq = _reflection.GeneratedProtocolMessageType('DebugReq', (_message.Message,), {
  'DESCRIPTOR' : _DEBUGREQ,
  '__module__' : 'debug.debug_pb2'
  # @@protoc_insertion_point(class_scope:cc.arduino.cli.debug.DebugReq)
  })
_sym_db.RegisterMessage(DebugReq)

DebugConfigReq = _reflection.GeneratedProtocolMessageType('DebugConfigReq', (_message.Message,), {
  'DESCRIPTOR' : _DEBUGCONFIGREQ,
  '__module__' : 'debug.debug_pb2'
  # @@protoc_insertion_point(class_scope:cc.arduino.cli.debug.DebugConfigReq)
  })
_sym_db.RegisterMessage(DebugConfigReq)

DebugResp = _reflection.GeneratedProtocolMessageType('DebugResp', (_message.Message,), {
  'DESCRIPTOR' : _DEBUGRESP,
  '__module__' : 'debug.debug_pb2'
  # @@protoc_insertion_point(class_scope:cc.arduino.cli.debug.DebugResp)
  })
_sym_db.RegisterMessage(DebugResp)

GetDebugConfigResp = _reflection.GeneratedProtocolMessageType('GetDebugConfigResp', (_message.Message,), {

  'ToolchainConfigurationEntry' : _reflection.GeneratedProtocolMessageType('ToolchainConfigurationEntry', (_message.Message,), {
    'DESCRIPTOR' : _GETDEBUGCONFIGRESP_TOOLCHAINCONFIGURATIONENTRY,
    '__module__' : 'debug.debug_pb2'
    # @@protoc_insertion_point(class_scope:cc.arduino.cli.debug.GetDebugConfigResp.ToolchainConfigurationEntry)
    })
  ,

  'ServerConfigurationEntry' : _reflection.GeneratedProtocolMessageType('ServerConfigurationEntry', (_message.Message,), {
    'DESCRIPTOR' : _GETDEBUGCONFIGRESP_SERVERCONFIGURATIONENTRY,
    '__module__' : 'debug.debug_pb2'
    # @@protoc_insertion_point(class_scope:cc.arduino.cli.debug.GetDebugConfigResp.ServerConfigurationEntry)
    })
  ,
  'DESCRIPTOR' : _GETDEBUGCONFIGRESP,
  '__module__' : 'debug.debug_pb2'
  # @@protoc_insertion_point(class_scope:cc.arduino.cli.debug.GetDebugConfigResp)
  })
_sym_db.RegisterMessage(GetDebugConfigResp)
_sym_db.RegisterMessage(GetDebugConfigResp.ToolchainConfigurationEntry)
_sym_db.RegisterMessage(GetDebugConfigResp.ServerConfigurationEntry)


DESCRIPTOR._options = None
_GETDEBUGCONFIGRESP_TOOLCHAINCONFIGURATIONENTRY._options = None
_GETDEBUGCONFIGRESP_SERVERCONFIGURATIONENTRY._options = None

_DEBUG = _descriptor.ServiceDescriptor(
  name='Debug',
  full_name='cc.arduino.cli.debug.Debug',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=869,
  serialized_end=1056,
  methods=[
  _descriptor.MethodDescriptor(
    name='Debug',
    full_name='cc.arduino.cli.debug.Debug.Debug',
    index=0,
    containing_service=None,
    input_type=_DEBUGREQ,
    output_type=_DEBUGRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetDebugConfig',
    full_name='cc.arduino.cli.debug.Debug.GetDebugConfig',
    index=1,
    containing_service=None,
    input_type=_DEBUGCONFIGREQ,
    output_type=_GETDEBUGCONFIGRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEBUG)

DESCRIPTOR.services_by_name['Debug'] = _DEBUG

# @@protoc_insertion_point(module_scope)
